"""initial

Revision ID: 424347248572
Revises: 
Create Date: 2023-10-17 00:34:20.911073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424347248572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reg_code', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('capital', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_reg_code'), 'company', ['reg_code'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('personal_code', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=False)
    op.create_index(op.f('ix_person_personal_code'), 'person', ['personal_code'], unique=True)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Integer(), nullable=False),
    sa.Column('is_person', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company_reg_code', sa.String(length=7), nullable=False),
    sa.Column('member_person_id', sa.Integer(), nullable=True),
    sa.Column('member_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_reg_code'], ['company.reg_code'], ),
    sa.ForeignKeyConstraint(['member_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['member_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_id'), 'membership', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_person_personal_code'), table_name='person')
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_company_reg_code'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
