"""initial

Revision ID: 87a9836b8ae3
Revises: 
Create Date: 2023-10-11 17:41:02.872125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a9836b8ae3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'total_capital')
    op.drop_column('company', 'founding_date')
    op.add_column('member', sa.Column('is_person', sa.Boolean(), nullable=False))
    op.add_column('member', sa.Column('is_founder', sa.Boolean(), nullable=False))
    op.drop_index('ix_member_name', table_name='member')
    op.drop_index('ix_member_personal_code', table_name='member')
    op.drop_column('member', 'name')
    op.drop_column('member', 'personal_code')
    op.drop_column('member', 'is_individual')
    op.add_column('membership', sa.Column('member_id', sa.Integer(), nullable=False))
    op.add_column('membership', sa.Column('copmany_id', sa.Integer(), nullable=False))
    op.alter_column('membership', 'capital',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'membership', 'member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'membership', 'company', ['copmany_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.drop_constraint(None, 'membership', type_='foreignkey')
    op.alter_column('membership', 'capital',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('membership', 'copmany_id')
    op.drop_column('membership', 'member_id')
    op.add_column('member', sa.Column('is_individual', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('personal_code', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index('ix_member_personal_code', 'member', ['personal_code'], unique=False)
    op.create_index('ix_member_name', 'member', ['name'], unique=False)
    op.drop_column('member', 'is_founder')
    op.drop_column('member', 'is_person')
    op.add_column('company', sa.Column('founding_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('total_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
